# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffc30c3d38558f0461ac75cddf6fac3685c0554db6b023cbf0ae1c634b2472bdedd5659cc9c7c194af8fecd48a83903e6565b1b75ce31cbc9949c3ca94ba52a6

test:
  secret_key_base: f0b1030e53a74db9b146d3f35c828adef6cba4a5f93cef7d4a882db00f3a8f0e709a764a3d74d44919aab0ed163dd4ab8e4ef8909761ae18cc06dbe331244e9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
